# Generated by Django 5.1.4 on 2026-03-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("empresa", models.CharField(blank=True, max_length=200)),
                ("contato", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "estagio",
                    models.CharField(
                        choices=[
                            ("prospeccao", "Prospecção"),
                            ("qualificacao", "Qualificação"),
                            ("proposta", "Proposta Enviada"),
                            ("negociacao", "Negociação"),
                            ("fechado_ganho", "Fechado Ganho"),
                            ("fechado_perdido", "Fechado Perdido"),
                        ],
                        default="prospeccao",
                        max_length=20,
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lead",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("titulo", models.CharField(max_length=300)),
                ("projeto_nome", models.CharField(blank=True, max_length=200)),
                ("data_emissao", models.DateField()),
                ("data_validade", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviada", "Enviada"),
                            ("negociacao", "Em Negociação"),
                            ("aprovada", "Aprovada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=15,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("condicoes_pagamento", models.CharField(blank=True, max_length=200)),
                ("prazo_execucao", models.CharField(blank=True, max_length=100)),
                ("observacoes", models.TextField(blank=True)),
                ("notas_tecnicas", models.TextField(blank=True)),
                (
                    "transacao_financeiro_ref",
                    models.CharField(blank=True, max_length=50),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propostas",
                        to="cadastros.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta",
                "verbose_name_plural": "Propostas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemProposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=300)),
                ("unidade", models.CharField(blank=True, max_length=20)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "preco_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("ordem", models.IntegerField(default=0)),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="vendas.proposta",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
            },
        ),
    ]
