# Generated by Django 5.1.4 on 2026-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="anexo_dados",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transacao",
            name="anexo_nome",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="transacao",
            name="anexo_tipo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transacao",
            name="recorrencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sem recorrência"),
                    ("semanal", "Semanal"),
                    ("quinzenal", "Quinzenal"),
                    ("mensal", "Mensal"),
                    ("bimestral", "Bimestral"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="transacao",
            name="recorrencia_grupo",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
