# Generated by Django 5.1.4 on 2026-03-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=300)),
                ("projeto_nome", models.CharField(blank=True, max_length=200)),
                (
                    "qtd_comprada",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "qtd_utilizada",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "preco_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("data_compra", models.DateField(blank=True, null=True)),
                ("data_validade", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cadastros.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material em Estoque",
                "verbose_name_plural": "Estoque de Materiais",
                "ordering": ["-data_compra", "-id"],
            },
        ),
    ]
