# Generated by Django 5.1.4 on 2026-03-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("projeto_nome", models.CharField(blank=True, max_length=200)),
                ("data_pedido", models.DateField()),
                ("data_entrega_prevista", models.DateField(blank=True, null=True)),
                ("data_entrega_real", models.DateField(blank=True, null=True)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("aprovacao", "Aguardando Aprovação"),
                            ("aprovada", "Aprovada"),
                            ("recebida", "Recebida"),
                            ("encerrada", "Encerrada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=15,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "transacao_financeiro_ref",
                    models.CharField(blank=True, max_length=50),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_compra",
                        to="cadastros.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Compra",
                "verbose_name_plural": "Pedidos de Compra",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=300)),
                ("codigo_material", models.CharField(blank=True, max_length=100)),
                ("unidade", models.CharField(blank=True, max_length=20)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "preco_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.pedidocompra",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
