# Generated by Django 5.1.4 on 2026-03-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contratos"),
                            ("empresa", "Doc. Empresa"),
                            ("seguro", "Seguros"),
                            ("funcionario", "Doc. Funcionários"),
                            ("cat", "CATs"),
                            ("procedimento", "Procedimentos"),
                            ("medicao", "Medições"),
                            ("nota", "Notas Fiscais"),
                            ("proposta", "Propostas"),
                            ("outro", "Outros"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=300)),
                ("observacoes", models.TextField(blank=True)),
                ("projeto_nome", models.CharField(blank=True, max_length=200)),
                ("arquivo_nome", models.CharField(blank=True, max_length=300)),
                ("arquivo_tipo", models.CharField(blank=True, max_length=100)),
                ("arquivo_dados", models.BinaryField(blank=True, null=True)),
                ("enviado_por", models.CharField(blank=True, max_length=150)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="cadastros.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "ordering": ["-criado_em"],
            },
        ),
    ]
